name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install Rust toolchain
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      # Step 3: Cache Dependencies to Speed Up Builds
      - name: Cache Cargo Dependencies
        uses: Swatinem/rust-cache@v2

      # Step 4: Run Formatting Check
      - name: Run rustfmt
        run: cargo fmt -- --check

      # Step 5: Lint with Clippy
      - name: Lint with Clippy
        run: cargo clippy -- -D warnings

      # Step 6: Run Tests
      - name: Run Tests
        run: cargo test --verbose
